import { VIPROQuestionsProps } from "./usa.vipro";

export const questionsSpanish: VIPROQuestionsProps[] = [
    { "question": "Nombre completo", "type_question": "abierta", "response": [""], "user_response": "", "category": "DATOS PERSONALES" },
    { "question": "Fecha de vencimiento de su pasaporte (Debe estar vigente mayor a 180 días mínimo)", "type_question": "abierta", "response": [""], "user_response": "", "category": "DATOS PERSONALES" },
    { "question": "Fecha de nacimiento", "type_question": "abierta", "response": [""], "user_response": "", "category": "DATOS PERSONALES" },
    { "question": "Estado civil", "type_question": "opcion multiple", "response": ["Soltero(a)", "Casado(a)", "Divorciado(a)", "Viudo(a)", "Unión Libre"], "user_response": "", "category": "DATOS PERSONALES" },
    { "question": "Ha solicitado visa americana anteriormente?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "DATOS PERSONALES" },
    { "question": "Le han negado una visa americana anteriormente?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "DATOS PERSONALES" },
    { "question": "Alguna vez ha entrado de manera ilegal a Estados Unidos?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "DATOS PERSONALES" },
    { "question": "Alguna vez ha sido deportado de Estados Unidos?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "DATOS PERSONALES" },
    { "question": "Alguna vez ha estado detenido?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "DATOS PERSONALES" },
    { "question": "Alguna vez le han cancelado una visa americana?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "DATOS PERSONALES" },
    { "question": "¿Qué tipo de visa solicita o desea obtener?", "type_question": "opcion multiple", "response": ["B1/B2 — Turismo y Negocios", "B1 — Negocios únicamente", "B2 — Turismo / Médica / Familiar", "Visa de Trabajo (H-1B / H-2B / L-1 / O-1)", "Visa de Estudiante (F-1 / J-1)", "Asilo / Protección Internacional", "Otro tipo de visa"], "user_response": "", "category": "DATOS PERSONALES" },

    { "question": "Sus padres si tienen visa americana?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Desea viajar a estados unidos por visita familiar?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Desea viajar a estados unidos por turismo?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Desea viajar a estados unidos por Negocios?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Desea Viajar a estados unidos para Trabajar", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Posee una carta de contrato enviada de parte de una empresa americana?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Tiene a un familiar en graves condiciones en Estados Unidos?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Su familiar es Residente o Ciudadano?", "type_question": "opcion multiple", "response": ["RESIDENTE", "CIUDADANO", "NO TENGO FAMILIAR EN ESE PAIS"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Su estancia en estados unidos será menor a 30 días?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Sus gastos de viaje serán pagados por otra persona?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Usted será el responsable de pagar su viaje a estados unidos?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Viaje por parte de un grupo, empresa u organización", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Posee una carta de invitación de una institución Privada o Pública para viajar a USA?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Ha aplicado a una visa Americana en los últimos 6 meses?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Tiene familiares inmediatos en estados Unidos (padres, hermanos, Hijos)", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Son Ciudadanos, Residentes, Otros.", "type_question": "opcion multiple", "response": ["CIUDADANOS", "RESIDENTES", "OTROS"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Alguien le está invitando a estados unidos?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Qué relación tiene con el invitante", "type_question": "opcion multiple", "response": ["FAMILIAR", "OTROS"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "El invitante es Ciudadano O Residente?", "type_question": "opcion multiple", "response": ["CIUDADANO", "RESIDENTE"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Su casa es Propia, Alquilada, hipotecada, Otros", "type_question": "opcion multiple", "response": ["Propia", "Alquilada", "Hipotecada", "Otros"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Posee una Constancia de estudio actualmente?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Posee una empresa legalmente inscrita que declare impuestos en su país?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "Ha viajado fuera de su país de manera legal anteriormente?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DE VIAJES" },
    { "question": "Ha viajado a otros países en los últimos 12 meses?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DE VIAJES" },
    { "question": "Ha viajado legalmente a más de 4 países en los últimos 5 años?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DE VIAJES" },
    { "question": "Alguna vez ha sido detenido en su país?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "Ha estado involucrado en alguna actividad delictiva que implique Drogas en su país?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "Está Empleado Actualmente?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "Posee solvencia de impuestos en su país?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "Posee ingresos mensuales similares o mayores a $1200.00 Mensuales?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "Posee una constancia laboral con al menos un año de antigüedad?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "Declara impuestos en su país?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "Qué nivel De Educación posee?", "type_question": "opcion multiple", "response": ["BASICO", "BACHILLER", "GRADUADO", "MASTER", "DOCTORADO", "ESPECIALIZACION"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "Estudia actualmente?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "Ha pertenecido al servicio militar?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "Ha pertenecido a una tribu o secta grupo no reconocido legalmente?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "¿Ha estado involucrado en algún delito en su país?", "type_question": "opcion multiple", "response": ["SÍ", "NO"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "¿Alguna vez ha servido, sido miembro o estado involucrado en una unidad paramilitar, unidad de autodefensa, grupo guerrillero u organización insurgente?", "type_question": "opcion multiple", "response": ["SÍ", "NO"], "user_response": "", "category": "HISTORIAL DELICTIVO" },
    { "question": "¿Tiene una petición formal o patrocinio de un patrono o empresa en Estados Unidos o el país de destino?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "ARRAIGOS FAMILIARES Y FINANCIEROS" },
    { "question": "¿Has sufrido daño o maltrato en tu país?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "PROTECCIÓN Y ASILO" },
    { "question": "¿Temes regresar a tu país?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "PROTECCIÓN Y ASILO" },
    { "question": "¿Has sido amenazado o planeas pedir asilo?", "type_question": "opcion multiple", "response": ["SI", "NO"], "user_response": "", "category": "PROTECCIÓN Y ASILO" }
];

export default questionsSpanish;
